(()=>{'use strict';
const $=id=>document.getElementById(id),V=['B2C','B2B','B2G','Carsharing'];
const S={salesFile:null,templateFile:null,sales:null,model:null};
const E={salesFile:$('salesFile'),templateFile:$('templateFile'),salesName:$('salesName'),templateName:$('templateName'),salesStatus:$('salesStatus'),templateStatus:$('templateStatus'),salesCard:$('salesCard'),templateCard:$('templateCard'),readyBadge:$('readyBadge'),buildBtn:$('buildBtn'),resetBtn:$('resetBtn'),printBtn:$('printBtn'),parseLog:$('parseLog'),reportSection:$('reportSection'),reportDate:$('reportDate'),sourceCount:$('sourceCount'),kpiGrid:$('kpiGrid'),verticalTable:$('verticalTable'),clientTable:$('clientTable'),qualityList:$('qualityList'),qualityBadge:$('qualityBadge'),changesList:$('changesList'),decisionList:$('decisionList'),periodBadge:$('periodBadge'),templateInfo:$('templateInfo'),hitlInfo:$('hitlInfo'),clientFilter:$('clientFilter'),approveCheck:$('approveCheck'),saveSnapshotBtn:$('saveSnapshotBtn'),downloadHtmlBtn:$('downloadHtmlBtn')};
const n=v=>String(v??'').replace(/\u00a0/g,' ').replace(/\s+/g,' ').trim();
const k=v=>n(v).toLowerCase().replace(/ё/g,'е');
const num=v=>{if(typeof v==='number'&&isFinite(v))return v;const x=Number(n(v).replace(/\s/g,'').replace(',','.').replace(/[^0-9.\-]/g,''));return isFinite(x)?x:0};
const fmt=v=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(v||0);
const safe=s=>n(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function vert(v){const s=k(v).replace(/\s/g,'');if(s.includes('b2c'))return'B2C';if(s.includes('b2b'))return'B2B';if(s.includes('b2g'))return'B2G';if(s.includes('carsharing')||s.includes('каршер'))return'Carsharing';return n(v)||'Не определено'}
function sheets(buf){if(!window.XLSX)throw new Error('Модуль Excel не загрузился. Обновите страницу Ctrl+F5.');const w=XLSX.read(buf,{type:'array',cellDates:true});return w.SheetNames.map(name=>({name,rows:XLSX.utils.sheet_to_json(w.Sheets[name],{header:1,defval:null,raw:true})}))}
function score(s,groups){const h=[s.name,...s.rows.slice(0,40).flat()].map(k).join('|');return groups.reduce((a,g)=>a+(g.some(x=>h.includes(x))?1:0),0)}
function pick(ss,g){return ss.slice().sort((a,b)=>score(b,g)-score(a,g))[0]}
function hr(rows,g){let bi=0,bs=-1;rows.slice(0,80).forEach((r,i)=>{const c=(r||[]).map(k);let s=0;g.forEach(x=>{if(x.some(t=>c.some(v=>v.includes(t))))s++});if(s>bs){bs=s;bi=i}});return bi}
function idx(h,t){h=h.map(k);for(const x of t){const i=h.findIndex(v=>v.includes(x));if(i>=0)return i}return-1}
function parseSales(ss){
  if(!ss.length)throw new Error('В Excel нет листов.');
  const sh=pick(ss,[['вертикаль','канал','направление'],['клиент','проект','компания'],['b2c','b2b','b2g','carsharing','каршер']]);
  if(!sh)throw new Error('Не удалось определить лист плана продаж.');
  const r=sh.rows;
  const hi=hr(r,[['вертикаль','канал','направление'],['клиент','проект','компания']]);
  const h=(r[hi]||[]).map(n);
  const iv=idx(h,['вертикаль','канал','направление']);
  const ic=idx(h,['клиент','проект','контрагент','компания']);
  const ir=idx(h,['регион','город']);
  const is=idx(h,['статус']);
  if(iv<0&&ic<0)throw new Error(`Лист «${sh.name}» найден, но не определены столбцы «Вертикаль/Канал» или «Клиент/Проект».`);
  const fixed=new Set([iv,ic,ir,is].filter(x=>x>=0));
  let pc=h.map((x,i)=>({h:x,i})).filter(x=>x.h&&!fixed.has(x.i)&&(/[0-9]{4}/.test(x.h)||/(январ|феврал|март|апрел|май|июн|июл|август|сентябр|октябр|ноябр|декабр|недел|week|итого)/i.test(x.h)));
  if(!pc.length){pc=h.map((x,i)=>({h:x,i})).filter(x=>x.h&&!fixed.has(x.i)&&r.slice(hi+1,hi+20).some(row=>typeof row?.[i]==='number'))}
  const rec=[];
  r.slice(hi+1).forEach((row,o)=>{
    const vv=iv>=0?row[iv]:null,c=ic>=0?n(row[ic]):'';
    if(!n(vv)&&!c)return;
    const values={};pc.forEach(p=>values[p.h]=num(row[p.i]));
    rec.push({row:hi+2+o,vertical:vert(vv),client:c,region:ir>=0?n(row[ir]):'',status:is>=0?n(row[is]):'',values,isAggregate:!c});
  });
  if(!rec.length)throw new Error(`Лист «${sh.name}» прочитан, но строки плана не распознаны.`);
  return{sheet:sh.name,records:rec,periods:[...new Set(rec.flatMap(x=>Object.keys(x.values)))]};
}
function snapshot(){try{return JSON.parse(localStorage.getItem('sales-plan-baseline')||'null')}catch{return null}}
function makeModel(sa){const periods=sa.periods.length?sa.periods:['Период'],verticals=V.map(v=>{const p={};periods.forEach(x=>{const a=sa.records.filter(r=>r.vertical===v&&r.isAggregate),d=sa.records.filter(r=>r.vertical===v&&!r.isAggregate),agg=a.reduce((s,r)=>s+num(r.values[x]),0),det=d.reduce((s,r)=>s+num(r.values[x]),0);p[x]={plan:a.length?agg:det,aggregate:a.length?agg:null,detail:det,delta:a.length?det-agg:0}});return{vertical:v,periods:p}}),clients=sa.records.filter(r=>!r.isAggregate&&['B2B','B2G','Carsharing'].includes(r.vertical)),issues=[];verticals.forEach(v=>periods.forEach(p=>{const x=v.periods[p];if(x.aggregate!=null&&x.delta!==0)issues.push({s:'bad',t:`${v.vertical}, ${p}: сумма клиентов ${fmt(x.detail)} ≠ агрегат ${fmt(x.aggregate)} (${x.delta>0?'+':''}${fmt(x.delta)})`})}));const totals={};periods.forEach(p=>totals[p]=verticals.reduce((s,v)=>s+(v.periods[p]?.plan||0),0));const ss={at:new Date().toISOString(),byClient:{}};clients.forEach(c=>ss.byClient[`${c.vertical}|${k(c.client)}`]={values:c.values,status:c.status,region:c.region});const old=snapshot(),changes=[];if(old){new Set([...Object.keys(old.byClient||{}),...Object.keys(ss.byClient)]).forEach(x=>{const a=old.byClient?.[x],b=ss.byClient?.[x],name=x.split('|')[1];if(!a&&b)changes.push({h:`Новый проект: ${name}`,t:'Добавлен в план'});else if(a&&!b)changes.push({h:`Проект исчез: ${name}`,t:'Отсутствует в текущем плане'});else if(a&&b){const ps=new Set([...Object.keys(a.values||{}),...Object.keys(b.values||{})]);ps.forEach(p=>{const av=num(a.values?.[p]),bv=num(b.values?.[p]);if(av!==bv)changes.push({h:`Объем: ${name}`,t:`${p}: ${fmt(av)} → ${fmt(bv)}`})});if(n(a.status)!==n(b.status))changes.push({h:`Статус: ${name}`,t:`${a.status||'—'} → ${b.status||'—'}`})}})}if(!changes.length)changes.push({h:old?'Существенных изменений нет':'База сравнения не сохранена',t:old?'Текущий план совпадает с сохраненным':'Сохраните текущий расчет для сравнения следующего среза'});return{periods,verticals,clients,issues,totals,snapshot:ss,changes}}
function render(m){E.reportSection.classList.remove('hidden');E.reportDate.textContent=new Date().toLocaleDateString('ru-RU');E.sourceCount.textContent='2/2';E.periodBadge.textContent=m.periods.join(' • ');E.templateInfo.textContent=`Шаблон презентации: ${S.templateFile?.name||'—'}`;E.kpiGrid.innerHTML=m.periods.slice(0,6).map(p=>`<div class="kpi"><span>${safe(p)}</span><strong>${fmt(m.totals[p])}</strong><small>автомобилей</small></div>`).join('');const vh=`<thead><tr><th>Вертикаль</th>${m.periods.map(p=>`<th class="num">${safe(p)}</th>`).join('')}<th>Контроль</th></tr></thead>`,vb=m.verticals.map(v=>{const bad=m.periods.some(p=>(v.periods[p]?.delta||0)!==0);return`<tr><td><strong>${v.vertical}</strong></td>${m.periods.map(p=>`<td class="num">${fmt(v.periods[p]?.plan||0)}</td>`).join('')}<td><span class="status-pill ${bad?'status-bad':'status-ok'}">${bad?'расхождение':'сходится'}</span></td></tr>`}).join('');E.verticalTable.innerHTML=vh+`<tbody>${vb}</tbody>`;renderClients(m.clients,m.periods);const q=m.issues.length;E.qualityBadge.textContent=q?`${q} проблем`:'OK';E.qualityList.innerHTML=q?m.issues.map(x=>`<div class="quality-item ${x.s}"><strong>${x.s==='bad'?'Проверить':'Внимание'}</strong>${safe(x.t)}</div>`).join(''):`<div class="quality-item ok"><strong>OK</strong>Агрегаты совпадают с детализацией.</div>`;E.changesList.innerHTML=m.changes.slice(0,12).map(x=>`<div class="change-item"><strong>${safe(x.h)}</strong>${safe(x.t)}</div>`).join('');E.decisionList.innerHTML=q?m.issues.slice(0,8).map(x=>`<span class="decision-chip">${safe(x.t)}</span>`).join(''):'<span class="decision-chip">Критичных расхождений в плане не обнаружено</span>';E.printBtn.disabled=!E.approveCheck.checked;E.reportSection.scrollIntoView({behavior:'smooth',block:'start'})}
function renderClients(rows,periods){const f=k(E.clientFilter?.value||''),data=rows.filter(r=>!f||k([r.vertical,r.client,r.region,r.status].join(' ')).includes(f));E.clientTable.innerHTML=`<thead><tr><th>Вертикаль</th><th>Клиент / проект</th><th>Регион</th>${periods.map(p=>`<th class="num">${safe(p)}</th>`).join('')}<th>Статус</th></tr></thead><tbody>${data.map(r=>`<tr><td>${safe(r.vertical)}</td><td><strong>${safe(r.client||'—')}</strong></td><td>${safe(r.region||'—')}</td>${periods.map(p=>`<td class="num">${fmt(r.values[p]||0)}</td>`).join('')}<td>${safe(r.status||'—')}</td></tr>`).join('')}</tbody>`}
function setStatus(kind,state,text){const card=kind==='sales'?E.salesCard:E.templateCard,status=kind==='sales'?E.salesStatus:E.templateStatus;card.classList.remove('loaded','error');status.className='upload-status';if(state==='loaded'){card.classList.add('loaded');status.classList.add('status-loaded')}else if(state==='error'){card.classList.add('error');status.classList.add('status-error')}else status.classList.add('status-empty');status.textContent=text}
function updateReady(){const c=[S.salesFile,S.templateFile].filter(Boolean).length;E.readyBadge.textContent=`${c} / 2`;E.readyBadge.classList.toggle('complete',c===2);E.buildBtn.disabled=c!==2;if(c===2)E.parseLog.textContent='Оба файла загружены. Можно формировать One Page.'}
E.salesFile.addEventListener('change',()=>{const f=E.salesFile.files?.[0]||null;S.salesFile=null;S.sales=null;if(!f){E.salesName.textContent='Файл не выбран';setStatus('sales','empty','Не загружен');updateReady();return}if(!/\.(xlsx|xls|xlsm)$/i.test(f.name)){E.salesName.textContent=f.name;setStatus('sales','error','Ошибка формата');E.parseLog.textContent='План продаж должен быть Excel-файлом: XLSX, XLS или XLSM.';updateReady();return}S.salesFile=f;E.salesName.textContent=f.name;setStatus('sales','loaded','Загружен');E.parseLog.textContent=`План продаж выбран: ${f.name} (${(f.size/1024/1024).toFixed(2)} МБ).`;updateReady()});
E.templateFile.addEventListener('change',()=>{const f=E.templateFile.files?.[0]||null;S.templateFile=null;if(!f){E.templateName.textContent='Файл не выбран';setStatus('template','empty','Не загружен');updateReady();return}if(!/\.pptx$/i.test(f.name)){E.templateName.textContent=f.name;setStatus('template','error','Ошибка формата');E.parseLog.textContent='Шаблон презентации должен быть файлом PPTX.';updateReady();return}S.templateFile=f;E.templateName.textContent=f.name;setStatus('template','loaded','Загружен');E.parseLog.textContent=`Шаблон презентации выбран: ${f.name} (${(f.size/1024/1024).toFixed(2)} МБ).`;updateReady()});
E.buildBtn.addEventListener('click',async()=>{if(!S.salesFile||!S.templateFile)return;E.buildBtn.disabled=true;E.buildBtn.textContent='Читаю Excel...';E.parseLog.textContent='Проверяю структуру плана продаж...';try{S.sales=parseSales(sheets(await S.salesFile.arrayBuffer()));S.model=makeModel(S.sales);setStatus('sales','loaded','Загружен и прочитан');E.parseLog.textContent=`Готово. План продаж прочитан: лист «${S.sales.sheet}», периодов: ${S.sales.periods.length}, строк: ${S.sales.records.length}.`;render(S.model)}catch(err){setStatus('sales','error','Файл загружен, ошибка чтения');E.parseLog.textContent=`Excel загружен, но не удалось распознать план: ${err.message||String(err)}`}finally{E.buildBtn.textContent='Сформировать One Page';E.buildBtn.disabled=false}});
E.clientFilter?.addEventListener('input',()=>{if(S.model)renderClients(S.model.clients,S.model.periods)});
E.approveCheck?.addEventListener('change',()=>{E.printBtn.disabled=!E.approveCheck.checked});
E.printBtn?.addEventListener('click',()=>window.print());
E.saveSnapshotBtn?.addEventListener('click',()=>{if(!S.model)return;localStorage.setItem('sales-plan-baseline',JSON.stringify(S.model.snapshot));E.saveSnapshotBtn.textContent='База сохранена'});
E.downloadHtmlBtn?.addEventListener('click',()=>{const blob=new Blob(['<!doctype html><meta charset="utf-8">'+$('onePage').outerHTML],{type:'text/html'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ATOM_Sales_OnePage.html';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});
E.resetBtn?.addEventListener('click',()=>{S.salesFile=S.templateFile=S.sales=S.model=null;E.salesFile.value='';E.templateFile.value='';E.salesName.textContent=E.templateName.textContent='Файл не выбран';setStatus('sales','empty','Не загружен');setStatus('template','empty','Не загружен');E.reportSection.classList.add('hidden');E.parseLog.textContent='Ожидаю загрузку файлов.';E.approveCheck.checked=false;E.printBtn.disabled=true;updateReady()});
setStatus('sales','empty','Не загружен');setStatus('template','empty','Не загружен');updateReady();
})();