(()=>{
const $=s=>document.querySelector(s), fmt=n=>(Number(n)||0).toLocaleString('ru-RU');
const strip=v=>String(v||'').replace(/\s*\[[^\]]+\]\s*$/,'').trim();
const key=h=>{const m=String(h||'').match(/\[([^\]]+)\]\s*$/);return m?m[1]:String(h||'').trim()};
const num=v=>{const n=Number(String(v??'').replace(/\s/g,'').replace(',','.').replace(/[^0-9.\-]/g,''));return Number.isFinite(n)?n:null};
const date=v=>{if(!v)return null;const s=String(v),m=s.match(/^(\d{1,2})\.(\d{1,2})\.(\d{4})/);if(m)return new Date(+m[3],+m[2]-1,+m[1]);const d=new Date(s);return isNaN(d)?null:d};
const vcat=v=>{const s=strip(v).toLowerCase();if(!s)return'Не указана';if(s.includes('corp')||s.includes('корп'))return'Корпоративные';if(s.includes('taxi')||s.includes('такс'))return'Такси';if(s.includes('delivery')||s.includes('достав'))return'Доставка';if(s==='gr'||s.includes('b2g'))return'GR / B2G';if(s.includes('carsharing')||s.includes('каршер'))return'Каршеринг';return strip(v)};
const SNAPSHOT_KEY='atom_b2b_crm_snapshot_v1';
let data=[], current=[];
function parse(matrix){const hs=(matrix[0]||[]).map(key),today=new Date();today.setHours(0,0,0,0);return matrix.slice(1).filter(r=>r.some(x=>String(x||'').trim())).map((r,i)=>{const o={};hs.forEach((h,j)=>o[h]=r[j]??'');const status=strip(o.__status)||'Не указана',active=status!=='Не указана'&&!/(неактив|дисквалиф)/i.test(status);const ds=[o._lastActivity,o.lastActivity,o.__statusChangedAt,o.__createdAt].map(date).filter(Boolean);const touch=ds.length?new Date(Math.max(...ds.map(x=>x.getTime()))):null,age=touch?Math.max(0,Math.floor((today-touch)/86400000)):null;return{id:o.__id||i+1,company:strip(o.lead_company_name||o._company)||strip(o.__name)||'Без названия',owner:strip(o._owner).replace(/\s+/g,' ')||'Не назначен',status,vertical:vcat(o.vertical),touch:touch?touch.toISOString():'',age,active,task:String(o.__tasks_earliest_duedate||''),fleet:num(o.fleet_size_number||o.fleet_size||o.lead_cars_amount),atom:num(o.lead_atom_amount||o.lead_electrocars_amount),phone:String(o.lead_phone||''),email:String(o.lead_email||''),inn:String(o.lead_inn||'')}})}

function recalcAge(row){if(!row.touch)return row;const d=new Date(row.touch);if(Number.isNaN(d.getTime()))return row;const today=new Date();today.setHours(0,0,0,0);row.age=Math.max(0,Math.floor((today-d)/86400000));return row}
function persistSnapshot(fileName){const payload={version:1,fileName:String(fileName||'Выгрузка ELMA'),savedAt:new Date().toISOString(),data};localStorage.setItem(SNAPSHOT_KEY,JSON.stringify(payload));return payload}
function showLoadedState(fileName,restored=false,savedAt=''){const source=String(fileName||'Выгрузка ELMA');$('#sourceName').textContent=source+' · '+fmt(data.length)+' строк';$('#dashboard').classList.remove('hidden');$('#emptyState').classList.add('hidden');$('#exportBtn').disabled=false;$('#clearBtn').disabled=false;const when=savedAt?new Date(savedAt):null;const suffix=when&&!Number.isNaN(when.getTime())?' · сохранено '+when.toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).replace(',',''):'';$('#fileStatus').textContent=restored?'Восстановлен последний сохранённый срез'+suffix+'.':'Готово. Данные сохранены в браузере и останутся после обновления страницы.';$('#fileStatus').className='statusline ok';summary()}
function restoreSnapshot(){try{const raw=localStorage.getItem(SNAPSHOT_KEY);if(!raw)return false;const saved=JSON.parse(raw);if(!saved||!Array.isArray(saved.data)||!saved.data.length)return false;data=saved.data.map(recalcAge);showLoadedState(saved.fileName,true,saved.savedAt);return true}catch(err){console.warn('CRM snapshot restore failed',err);return false}}
function count(arr,k){return arr.reduce((m,r)=>(m[r[k]||'Не указано']=(m[r[k]||'Не указано']||0)+1,m),{})}
function bars(id,obj){const e=$(id),a=Object.entries(obj).sort((x,y)=>y[1]-x[1]),mx=Math.max(1,...a.map(x=>x[1]));e.innerHTML=a.map(([k,v])=>`<div class="bar-row"><div>${k}</div><div class="bar-track"><div class="bar" style="width:${v/mx*100}%"></div></div><div class="bar-val">${fmt(v)}</div></div>`).join('')}
function summary(){const a=data.filter(x=>x.active),live=a.filter(x=>x.age!=null&&x.age<=30),stale=a.filter(x=>x.age!=null&&x.age>90),task=a.filter(x=>x.task);$('#kTotal').textContent=fmt(data.length);$('#kActive').textContent=fmt(a.length);$('#kLive').textContent=fmt(live.length);$('#kStale').textContent=fmt(stale.length);$('#kTasks').textContent=fmt(task.length);bars('#statusBars',count(a,'status'));bars('#verticalBars',count(a,'vertical'));const owners=count(a,'owner');$('#owners').innerHTML=Object.entries(owners).sort((x,y)=>y[1]-x[1]).map(([o,n])=>`<tr><td>${o}</td><td class="num"><b>${fmt(n)}</b></td><td class="num">${fmt(a.filter(x=>x.owner===o&&x.age!=null&&x.age<=30).length)}</td><td class="num">${fmt(a.filter(x=>x.owner===o&&x.age!=null&&x.age>90).length)}</td><td class="num">${fmt(a.filter(x=>x.owner===o&&x.task).length)}</td></tr>`).join('');
const q=[['Компания',x=>x.company&&x.company!=='Без названия'],['Вертикаль',x=>x.vertical!=='Не указана'],['Телефон',x=>x.phone],['Email',x=>x.email],['ИНН',x=>x.inn],['Автопарк',x=>x.fleet!=null],['Кол-во ATOM',x=>x.atom!=null],['След. задача',x=>x.task]];$('#quality').innerHTML=q.map(([n,f])=>{const p=a.length?Math.round(a.filter(f).length/a.length*100):0;return`<div class="qrow"><div>${n}</div><div class="qbar"><span style="width:${p}%"></span></div><div class="qval">${p}%</div></div>`}).join('');
const activeStatuses=[...new Set(a.map(x=>x.status))].sort();setupMulti('#fStatus',[...activeStatuses,'Неактивные / дисквалифицированные'],activeStatuses);setupMulti('#fVertical',Object.keys(count(a,'vertical')).sort(),[]);setupMulti('#fOwner',Object.keys(owners).sort(),[]);setupMulti('#fHealth',['≤30 дней','31-90 дней','>90 дней','Нет даты','Неактивный'],[]);apply()}
function setupMulti(id,items,selected=[]){const el=$(id);el._values=new Set(selected);el.innerHTML=`<button type="button" class="multi-trigger"><span class="multi-label"></span><span class="multi-chevron">⌄</span></button><div class="multi-menu"><div class="multi-actions"><button type="button" data-ms-all>Выбрать все</button><button type="button" data-ms-clear>Очистить</button></div><div class="multi-options"></div></div>`;const opts=el.querySelector('.multi-options');items.forEach(v=>{const row=document.createElement('label');row.className='multi-option';const cb=document.createElement('input');cb.type='checkbox';cb.value=v;cb.checked=el._values.has(v);const span=document.createElement('span');span.textContent=v;row.append(cb,span);opts.append(row);cb.addEventListener('change',()=>{cb.checked?el._values.add(v):el._values.delete(v);updateMultiLabel(el);apply()})});el.querySelector('.multi-trigger').addEventListener('click',e=>{e.stopPropagation();document.querySelectorAll('.multi-select.open').forEach(x=>{if(x!==el)x.classList.remove('open')});el.classList.toggle('open')});el.querySelector('[data-ms-all]').addEventListener('click',()=>{el._values=new Set(items);opts.querySelectorAll('input').forEach(x=>x.checked=true);updateMultiLabel(el);apply()});el.querySelector('[data-ms-clear]').addEventListener('click',()=>{el._values.clear();opts.querySelectorAll('input').forEach(x=>x.checked=false);updateMultiLabel(el);apply()});updateMultiLabel(el)}
function updateMultiLabel(el){const n=el._values?.size||0,total=el.querySelectorAll('.multi-option input').length,label=el.querySelector('.multi-label');if(!n||n===total)label.textContent='Все';else if(n===1)label.textContent=[...el._values][0];else label.textContent=n+' выбрано'}
function selected(id){return $(id)._values||new Set()}
document.addEventListener('click',e=>{if(!e.target.closest('.multi-select'))document.querySelectorAll('.multi-select.open').forEach(x=>x.classList.remove('open'))});
function health(r){if(!r.active)return'Неактивный';if(r.age==null)return'Нет даты';if(r.age<=30)return'≤30 дней';if(r.age<=90)return'31-90 дней';return'>90 дней'}
function apply(){const q=$('#fSearch').value.toLowerCase(),ss=selected('#fStatus'),vs=selected('#fVertical'),os=selected('#fOwner'),hs=selected('#fHealth'),inactiveSelected=ss.has('Неактивные / дисквалифицированные');current=data.filter(r=>(!ss.size||ss.has(r.status)||(inactiveSelected&&!r.active))&&(!vs.size||vs.has(r.vertical))&&(!os.size||os.has(r.owner))&&(!hs.size||hs.has(health(r)))&&(!q||[r.company,r.inn,r.owner,r.phone,r.email].some(x=>String(x||'').toLowerCase().includes(q))));$('#resultCount').textContent=`Показано ${fmt(current.length)} из ${fmt(data.length)}`;$('#tbody').innerHTML=current.slice(0,600).map(r=>`<tr><td class="company">${r.company}</td><td>${r.status}</td><td>${r.vertical}</td><td>${r.owner}</td><td><span class="pill ${r.age!=null&&r.age<=30?'live':r.age>90?'stale':'mid'}">${health(r)}</span></td><td class="num">${r.age??''}</td><td>${r.task||'<span class="muted">нет</span>'}</td><td class="num">${r.fleet??''}</td><td class="num">${r.atom??''}</td><td>${r.phone||r.email?'✓':''}</td></tr>`).join('')}
function csv(){const c=[['Компания','company'],['Статус','status'],['Вертикаль','vertical'],['Ответственный','owner'],['Дней','age'],['Задача','task'],['Автопарк','fleet'],['ATOM','atom'],['Телефон','phone'],['Email','email'],['ИНН','inn']],q=v=>'"'+String(v??'').replaceAll('"','""')+'"';const lines=[c.map(x=>q(x[0])).join(';'),...current.map(r=>c.map(x=>q(r[x[1]])).join(';'))];const b=new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='ATOM_B2B_CRM.csv';a.click()}
$('#crmFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const wb=XLSX.read(await f.arrayBuffer(),{type:'array'}),ws=wb.Sheets[wb.SheetNames[0]],m=XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:false});data=parse(m);const saved=persistSnapshot(f.name);showLoadedState(f.name,false,saved.savedAt)}catch(err){$('#fileStatus').textContent='Ошибка: '+err.message;$('#fileStatus').className='statusline bad'}};
$('#fSearch').addEventListener('input',apply);$('#exportBtn').onclick=csv;$('#resetBtn').onclick=()=>{$('#fSearch').value='';const a=data.filter(x=>x.active),activeStatuses=[...new Set(a.map(x=>x.status))].sort();setupMulti('#fStatus',[...activeStatuses,'Неактивные / дисквалифицированные'],activeStatuses);setupMulti('#fVertical',[...new Set(a.map(x=>x.vertical))].sort(),[]);setupMulti('#fOwner',[...new Set(a.map(x=>x.owner))].sort(),[]);setupMulti('#fHealth',['≤30 дней','31-90 дней','>90 дней','Нет даты','Неактивный'],[]);apply()};$('#clearBtn').onclick=()=>{localStorage.removeItem(SNAPSHOT_KEY);location.reload()};restoreSnapshot();
})();

(()=>{const U='https://enlyiedwkarajvfsilel.supabase.co',K='sb_publishable_YK0GMEpWNTnEp3ImIvONKQ_3IPZdvq5',gate=document.getElementById('authGate'),shell=document.getElementById('appShell'),st=document.getElementById('authStatus'),mail=document.getElementById('authEmail'),send=document.getElementById('authSend'),user=document.getElementById('authUserEmail');let sb=null;try{sb=window.supabase?.createClient(U,K,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,flowType:'implicit',storageKey:'atom-sales-plan-auth'}})}catch{}const ok=e=>/^[^@\s]+@atom\.team$/i.test(e||'');const show=e=>{gate.classList.add('app-hidden');shell.classList.remove('app-hidden');user.textContent=e};async function open(s){if(!s?.access_token)return false;try{const{data,error}=await sb.auth.getUser(s.access_token);if(error||!ok(data.user?.email))return false;localStorage.setItem('atom_access_token',s.access_token);if(s.refresh_token)localStorage.setItem('atom_refresh_token',s.refresh_token);show(data.user.email);return true}catch{return false}}async function boot(){if(!sb){st.textContent='Не удалось загрузить модуль входа.';return}try{const{data}=await sb.auth.getSession();if(data.session&&await open(data.session))return;const a=localStorage.getItem('atom_access_token'),r=localStorage.getItem('atom_refresh_token');if(a&&r){const x=await sb.auth.setSession({access_token:a,refresh_token:r});if(x.data.session&&await open(x.data.session))return}}catch{}st.textContent='Введите рабочую почту @atom.team. Пароль не нужен.'}send.onclick=async()=>{const e=mail.value.trim().toLowerCase();if(!ok(e)){st.textContent='Доступ разрешен только для @atom.team.';st.className='auth-status bad';return}send.disabled=true;st.textContent='Отправляю ссылку...';try{const r=await fetch(U+'/functions/v1/atom-magic-auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:e})});if(!r.ok)throw new Error('Не удалось отправить ссылку');st.textContent='Ссылка отправлена на '+e+'.';st.className='auth-status ok'}catch(err){st.textContent=err.message;st.className='auth-status bad'}finally{send.disabled=false}};mail.addEventListener('keydown',e=>{if(e.key==='Enter')send.click()});document.getElementById('authLogout').onclick=async()=>{try{await sb.auth.signOut({scope:'local'})}catch{}localStorage.removeItem('atom_access_token');localStorage.removeItem('atom_refresh_token');location.reload()};sb?.auth.onAuthStateChange(async(ev,s)=>{if((ev==='SIGNED_IN'||ev==='TOKEN_REFRESHED')&&s)await open(s)});boot()})();